### ISSUE TITLE
Error on wget statement. file does exist at url.

### ISSUE THREAD

**Issue by lukeholder** [donnykurnia/Railscasts-downloader#2]
Error on wget statement. file does exist at url.

```
"Reading http://railscasts.com ..."
"will download http://railscasts.com/episodes/382-tagging"
"Downloading 382-tagging.mp4"
./railscasts-downloader.rb:63:in ``': No such file or directory - wget http://media.railscasts.com/assets/episodes/videos/382-tagging.mp4 -c -O 382-tagging.mp4.tmp  (Errno::ENOENT)
    from ./railscasts-downloader.rb:63:in `block (2 levels) in download_videos'
    from /Users/lukeholder/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/nokogiri-1.5.5/lib/nokogiri/xml/node_set.rb:239:in `block in each'
    from /Users/lukeholder/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/nokogiri-1.5.5/lib/nokogiri/xml/node_set.rb:238:in `upto'
    from /Users/lukeholder/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/nokogiri-1.5.5/lib/nokogiri/xml/node_set.rb:238:in `each'
    from ./railscasts-downloader.rb:57:in `block in download_videos'
    from ./railscasts-downloader.rb:53:in `each'
    from ./railscasts-downloader.rb:53:in `download_videos'
    from ./railscasts-downloader.rb:89:in `<main>'
```

**Comment by donnykurnia** [comment]
Is the error only for episode 382 or happened in other episodes?

It have been a while since I use this script, so I'm not aware for the possible bug.

Thanks for the notice.

**Comment by tomascharad** [comment]
I have the same problem... now with ep 417
